---
language: python
python: "2.7"

services:
  - docker

before_install:
  # Make sure everything's up to date.

install:

  # Add ansible.cfg to pick up roles path.

script:
  # We'll add some commands to test the role here.
