---
# Install task file for syslog-ng
- name: Install openssl
  yum:
    name: openssl
    state: present

- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install Syslog-ng
  yum:
    name: syslog-ng
    state: present
